[tool.poetry]
name = "code-names-bot-text-graph"
version = "0.1.0"
description = ""
authors = ["Nalu Zou"]
readme = "README.md"
packages = [{include = "code_names_bot_text_graph"}]

[tool.poetry.dependencies]
python = "^3.10"
black = "^22.8.0"
isort = "^5.10.1"

[tool.poetry.scripts]
format                                  = "tasks:format"

create-lemma-sense-map                  = "code_names_bot_text_graph.sense_proposal.create_lemma_sense_map:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
